version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" # adjust if your .csproj is in a subfolder
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # Skip only major updates
    assignees:
      - adamziv
    labels:
      - dependencies
      - automerge:disabled
