version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-lts
    container_name: dev_sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "sang192,albs"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P sang192,albs -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:
