version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword@!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -U sa -P Sang192albs@ -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
    ports:
      - "5000:5000" # change as needed
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=YourDbName;User=sa;Password=Sang192albs@
