global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "ci.yaml"
  - "dependabot.yml"

scrape_configs:
  - job_name: 'dotnet-tbd-app'
    static_configs:
      - targets: [ 'localhost:5000' ]  # Your .NET app service name and port
    scrape_interval: 5s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
